import { IGlobalKey } from './IGlobalKey';

/**
 * A global key event generated by the key server
 */
export type IGlobalKeyEvent = {
	vKey: number;
	rawKey: {
		_nameRaw: string;
		name: string;
	};
	name?: IGlobalKey;
	state: 'DOWN' | 'UP';
	scanCode: number;
	_raw: string;
};
